name: postman

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3️⃣ Install Newman + HTML reporter
      - name: Install Newman and htmlextra reporter
        run: npm install -g newman newman-reporter-htmlextra

      # 4️⃣ Run Postman Collection with Environment
      - name: Run Postman Collection
        run: |
          newman run "Token_base_authentication.postman_collection.json" \
            -e "Test_Environment.postman_environment.json" \
            -r cli,htmlextra \
            --reporter-htmlextra-export report.html

      # 5️⃣ Upload HTML report as artifact
      - name: Upload Newman HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: report.html
